### ISSUE TITLE
NameError: global name 'np' is not defined

### ISSUE THREAD

**Issue by luiscruz** [forrestbao/pyeeg#14]
I have installed pyeeg using pip. This is my line in requirements.txt:

```
-e git+https://github.com/forrestbao/pyeeg.git#egg=pyeeg
```

When I use pyeeg.ap_entropy I am encountering the following error:

```
NameError: global name 'np' is not defined
```

I have numpy installed, I'm importing it as np, and it works fine.
Do you have any idea what this might be?

Thanks!

**Comment by luiscruz** [comment]
I'm trying to run it using an ipython notebook

**Comment by luiscruz** [comment]
I guess here https://github.com/forrestbao/pyeeg/blob/master/pyeeg/__init__.py#L532
The code should consistently use numpy instead of np.

**Comment by Borzou** [comment]
Hi Luis,

Yes you are right. It seems that I missed changing nps in the sample
entropy and the approximate entropy. Will fix that asap. Thanks for sharing
it. In the meanwhile you can fix them for your own project. Please let us
know if you find any other problems.

Thanks,
Best Wishes,
Borzou

**Comment by luiscruz** [comment]
Will do! Thank you @Borzou

**Comment by ErikHendriks** [comment]
Or you could import numpy like this
import numpy as np
