### ISSUE TITLE
Information Based Similarity run error

### ISSUE THREAD

**Issue by thosvarley** [forrestbao/pyeeg#24]
When I try to run the example code for Information Based Similarity it returns:

information_based_similarity(test1, test2, 8)
Traceback (most recent call last):

  File "<ipython-input-104-d0b0a2517f12>", line 1, in <module>
    information_based_similarity(test1, test2, 8)

  File "/home/tfv21/anaconda3/lib/python3.6/site-packages/pyeeg/__init__.py", line 955, in information_based_similarity
    Wm.append(embed_seq(SymbolicSeq[0], 1, n).tolist())

  File "/home/tfv21/anaconda3/lib/python3.6/site-packages/pyeeg/__init__.py", line 161, in embed_seq
    shape = (X.size - Tau * (D - 1), D)

AttributeError: 'list' object has no attribute 'size'

I tried changing X.size to len(X), but that threw the same error in the same function (list object has no attribute 'itemsize.' 

Please advise.

**Comment by gemeinl** [comment]
You can solve this issue by casting the SymbolicSeq list to a numpy ndarray:

Add
SymbolicSeq = numpy.array(SymbolicSeq) 
in line 953.

https://github.com/forrestbao/pyeeg/blob/master/pyeeg/__init__.py#L953

**Comment by forrestbao** [comment]
Fixed by typecasting X at the beginning of embed_seq() in commit fdfb243b593e421f49be283f9c4ebbffdb1dcdb3
