### ISSUE TITLE
About the naming conventions in pyeeg

### ISSUE THREAD

**Issue by liubenyuan** [forrestbao/pyeeg#7]
Hi,

Thanks for this module and I am going to use it in my project.

I think there should be a `pyeeg.py` in the `pyeeg/` folder, and write a new `__init__.py` file to manually import all the relevant module. like

``` python
__all__ = ['hurst', 'lle']

from .pyeeg import hurst, lle
```

it's more python and follows the >3.3 standard

**Comment by liubenyuan** [comment]
And later on, if your are going to add more submodules or modules to this project, it world make the work much easier.

**Comment by forrestbao** [comment]
Ultimately fixed in commits ad90f28478db59e79cac5579a679c47deb3f52bf and 5444dd6e45a5f549a2e03a0552a9ba4f11afd54b
