### ISSUE TITLE
About pull request to this repository

### ISSUE THREAD

**Issue by liubenyuan** [forrestbao/pyeeg#8]
Hi,

I issued a pull request
to 
`https://github.com/jbergantine/pyeeg`
from
`https://github.com/mfeit/pyeeg`

it is possible to merge the pull request to this repository or do I need to create a new pull request ?

**Comment by bergantine** [comment]
@forrestbao I think this can be closed. https://github.com/mfeit/pyeeg returns a 404. @liubenyuan if this is still something, do you want to make a new pull request? The repo at the @jbergantine username is my development fork of @forrestbao 's original code.
